server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  jpa:
    hibernate.dll-auth: update
    generate-ddl: true
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dad_auth
    username: root
    password:


eureka:
client:
  serviceUrl:
    defaultZone: ${EUREKA_URI:http://localhost:1031/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${randow.value}}